services:
  trackme:
    build:
      context: .
      dockerfile: Dockerfile
    image: trackme
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - trackme-certs:/app/certs

volumes:
  trackme-certs:
